import Head from "next/head";
import Image from "next/image";
import Script from "next/script";

import Header from "@components/Header";
import Container from "@components/Container";
import Button from "@components/Button";

import styles from "@styles/Home.module.scss";

import products from "@data/products.json";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <Container>
                    <h1>Sick merch</h1>
                    <h2>Available merch</h2>
                    <ul className={styles.products}>
                        {products.map((product) => {
                            return (
                                <li key={product.id}>
                                    <Image
                                        src={product.image}
                                        height="1000"
                                        width="1000"
                                        alt={`Product ${product.title}`}
                                    />
                                    <h3 className={styles.productTitle}>
                                        {product.title}
                                    </h3>
                                    <p className={styles.productPrice}>
                                        {`£${product.price}`}
                                    </p>
                                    <p>
                                        <Button
                                            className="snipcart-add-item"
                                            data-item-id={product.id}
                                            data-item-price={product.price}
                                            data-item-url="/"
                                            data-item-description=""
                                            data-item-image={product.image}
                                            data-item-name={product.title}
                                        >
                                            Add to cart
                                        </Button>
                                    </p>
                                </li>
                            );
                        })}
                    </ul>
                </Container>
            </main>

            <footer className={styles.footer}>
                &copy; Sick merch, {new Date().getFullYear()}
            </footer>

            <Script src="https://cdn.snipcart.com/themes/v3.3.0/default/snipcart.js" />
            <div
                id="snipcart"
                data-config-modal-style="side"
                data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}
                data-currency="gbp"
                hidden
            ></div>
        </div>
    );
}
